apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: brokeredinfraconfigs.admin.enmasse.io
spec:
  group: admin.enmasse.io
  names:
    kind: BrokeredInfraConfig
    listKind: BrokeredInfraConfigList
    plural: brokeredinfraconfigs
    singular: brokeredinfraconfig
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: BrokeredInfraConfig is the Schema for the brokeredinfraconfigs
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BrokeredInfraConfigSpec defines the desired state of BrokeredInfraConfig
          properties:
            admin:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file'
              properties:
                resources:
                  properties:
                    memory:
                      type: string
                    storage:
                      type: string
                  required:
                  - memory
                  - storage
                  type: object
              required:
              - resources
              type: object
            broker:
              properties:
                addressFullPolicy:
                  type: string
                resources:
                  properties:
                    memory:
                      type: string
                    storage:
                      type: string
                  required:
                  - memory
                  - storage
                  type: object
              required:
              - addressFullPolicy
              - resources
              type: object
          required:
          - admin
          - broker
          type: object
        status:
          description: BrokeredInfraConfigStatus defines the observed state of BrokeredInfraConfig
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
