apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: consoleservices.admin.enmasse.io
spec:
  group: admin.enmasse.io
  names:
    kind: ConsoleService
    listKind: ConsoleServiceList
    plural: consoleservices
    singular: consoleservice
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            certificateSecret:
              description: SecretReference represents a Secret Reference. It has enough
                information to retrieve secret in any namespace
              properties:
                name:
                  description: Name is unique within a namespace to reference a secret
                    resource.
                  type: string
                namespace:
                  description: Namespace defines the space within which the secret
                    name must be unique.
                  type: string
              type: object
            discoveryMetadataURL:
              type: string
            host:
              type: string
            oauthClientSecret:
              description: SecretReference represents a Secret Reference. It has enough
                information to retrieve secret in any namespace
              properties:
                name:
                  description: Name is unique within a namespace to reference a secret
                    resource.
                  type: string
                namespace:
                  description: Namespace defines the space within which the secret
                    name must be unique.
                  type: string
              type: object
            scope:
              type: string
            ssoCookieDomain:
              type: string
            ssoCookieSecret:
              description: SecretReference represents a Secret Reference. It has enough
                information to retrieve secret in any namespace
              properties:
                name:
                  description: Name is unique within a namespace to reference a secret
                    resource.
                  type: string
                namespace:
                  description: Namespace defines the space within which the secret
                    name must be unique.
                  type: string
              type: object
          type: object
        status:
          properties:
            caCertSecret:
              description: SecretReference represents a Secret Reference. It has enough
                information to retrieve secret in any namespace
              properties:
                name:
                  description: Name is unique within a namespace to reference a secret
                    resource.
                  type: string
                namespace:
                  description: Namespace defines the space within which the secret
                    name must be unique.
                  type: string
              type: object
            host:
              type: string
            port:
              type: integer
          type: object
      required:
      - spec
      - status
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
