apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: addressplans.enmasse.io
spec:
  group: enmasse.io
  names:
    kind: AddressPlan
    listKind: AddressPlanList
    plural: addressplans
    singular: addressplan
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: AddressPlan is the Schema for the addressplans API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AddressPlanSpec defines the desired state of AddressPlan
          properties:
            addressType:
              type: string
            displayName:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file'
              type: string
            displayOrder:
              type: integer
            longDescription:
              type: string
            partitions:
              type: integer
            resources:
              properties:
                broker:
                  type: string
                router:
                  type: string
              required:
              - broker
              - router
              type: object
            shortDescription:
              type: string
          required:
          - addressType
          - displayName
          - displayOrder
          - longDescription
          - partitions
          - resources
          - shortDescription
          type: object
        status:
          description: AddressPlanStatus defines the observed state of AddressPlan
          type: object
      type: object
  version: v1beta2
  versions:
  - name: v1beta2
    served: true
    storage: true
