apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: addressspaceplans.enmasse.io
spec:
  group: enmasse.io
  names:
    kind: AddressSpacePlan
    listKind: AddressSpacePlanList
    plural: addressspaceplans
    singular: addressspaceplan
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: AddressSpacePlan is the Schema for the addressspaceplans API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AddressSpacePlanSpec defines the desired state of AddressSpacePlan
          properties:
            addressPlans:
              items:
                type: string
              type: array
            addressSpaceType:
              type: string
            displayName:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file'
              type: string
            displayOrder:
              type: integer
            infraConfigRef:
              type: string
            longDescription:
              type: string
            resourceLimits:
              properties:
                aggregate:
                  type: string
                broker:
                  type: string
                router:
                  type: string
              required:
              - aggregate
              - broker
              - router
              type: object
            shortDescription:
              type: string
          required:
          - addressPlans
          - addressSpaceType
          - displayName
          - displayOrder
          - infraConfigRef
          - longDescription
          - resourceLimits
          - shortDescription
          type: object
        status:
          description: AddressSpacePlanStatus defines the observed state of AddressSpacePlan
          type: object
      type: object
  version: v1beta2
  versions:
  - name: v1beta2
    served: true
    storage: true
